### ISSUE TITLE
طلب توحيد رقم الإصدار

### ISSUE THREAD

**Issue by akarimg** [ojuba-org/monajat#6]
السلام عليكم
بارك الله فيكم على تقديم هذا البرنامج المميز

المشكلة أن كل من الملفات التالية يحتوى على رقم إصدار مختلف
monajat.spec
NEWS
setup.py
أيضا رابط الإصدارات به أرقام مختلفة
https://github.com/ojuba-org/monajat/releases

أرجو أن يكون هناك توحيد لرقم الإصدار بهذه الملفات أو إزالته من الملفات غير المهمة
فأي هته الأرقام يمكن أن نعتبرها رقم الإصدار المعمول به؟

**Comment by muayyad-alsadi** [comment]
المعتمد هو ال
git tag

البقية عبارة عن نسخ قديمة للإصدارة السابقة (المتدحرجة إن شئت)

**Comment by moceap** [comment]
Solved

**Comment by akarimg** [comment]
ممتاز
شكرا أخي مؤيد
شكرا أخي @moceap وجزاك الله خيرا على التعديل
